/* TODO: Add this back in when the split deployment is implemented
variable "flag_split_deployment_persona" {
  type        = string
  default     = "lza"
  description = <<DESCRIPTION
Flag to indicate which part to deploy in a split deployment scenario.

Valid values are:
- `build` - Deploy only the initial VNet, Bastion, and build machine resources for the build environment
- `lza` - Deploy the complete landing zone resources including all AI/ML services and networking components

This allows for staged deployments where infrastructure can be deployed in phases.
DESCRIPTION
}
*/
variable "location" {
  type        = string
  description = <<DESCRIPTION
Azure region where all resources should be deployed.

This specifies the primary Azure region for deploying the AI/ML landing zone infrastructure. All resources will be created in this region unless specifically configured otherwise in individual resource definitions.
DESCRIPTION
  nullable    = false
}

# This is required for most resource modules
variable "resource_group_name" {
  type        = string
  description = <<DESCRIPTION
The name of the resource group where all resources will be deployed.

This resource group will contain all the AI/ML landing zone infrastructure components. The resource group should already exist or will be created as part of the deployment process.
DESCRIPTION
}

variable "enable_telemetry" {
  type        = bool
  default     = true
  description = <<DESCRIPTION
This variable controls whether or not telemetry is enabled for the module.
For more information see <https://aka.ms/avm/telemetryinfo>.
If it is set to false, then no telemetry will be collected.
DESCRIPTION
  nullable    = false
}

variable "flag_platform_landing_zone" {
  type        = bool
  default     = true
  description = <<DESCRIPTION
Flag to indicate if the platform landing zone is enabled.

If set to true, the module will deploy resources and connect to a platform landing zone hub. This enables integration with existing hub-and-spoke network architectures and centralized management services.
DESCRIPTION
}

variable "name_prefix" {
  #TODO: add a validation rule to keep this under 10 characters only alphanumeric lowercase
  type        = string
  default     = null
  description = <<DESCRIPTION
Optional prefix to be used for naming resources.

This prefix will be applied to all resource names generated by the module. It is useful for ensuring consistent naming conventions across deployments without requiring explicit names for each resource. The prefix should be kept under 10 characters and use only alphanumeric lowercase characters to avoid Azure naming limitations.
DESCRIPTION
}

variable "tags" {
  type        = map(string)
  default     = null
  description = <<DESCRIPTION
Map of tags to be assigned to all resources created by this module.

Tags are key-value pairs that help organize and manage Azure resources. These tags will be applied to all resources created by the module, enabling consistent resource governance, cost tracking, and operational management across the AI/ML landing zone infrastructure.
DESCRIPTION
}
